---
part: 1

title: Elements of Set Theory
author: H. Enderton
year: 1977

tags: meta/article/section
output: pdf_document
---

# Baby Set Theory
> part of [[Elements of Set Theory]]

\tableofcontents

<br>

## 1.0 Set

A *set* is a collection of things (called its members or elements), the collection being regarded as a single object. We write $t \in A$ to say that $t$ is a member of $A$, and we write $t \notin A$ to say that $t$ is not a member of $A$.

---

<br>

## 1.1 Principle of Extensionality

If two sets have exactly the same members, then they are equal.

If $A$ and $B$ are sets such that for every object $t$,
$$
t \in A  \quad \text{iff} \quad t \in B
$$
then $A=B$

---

<br>

## 1.2 Union and Intersection

The **union** of sets $A$ and $B$ is the set $A \cup B$ of all things that are members of $A$ or $B$ (or both).

Similarly, the **intersection** of $A$ and $B$ is the set $A \cap B$ of all things that are members of both $A$ and $B$.

Sets $A$ and $B$ are said to be **disjoint** when they have no common members, i.e. when $A \cup B = \emptyset$.

A set $A$ is said to be a **subset** of a set $B$ iff all the memebrs of $A$ are also members of $B$. Note that any set is a subset of itself.

---




