---
title: A History of Logic
author: Various Authors
published: N/A
tags: meta/philosophy/logic
date: 02/26/2023
output:
   pdf_document:
       latex_engine: xelatex
# page setup
classoption: a4paper
geometry: "left=3cm,right=3cm,top=1.5cm,bottom=3cm"
fontsize: 12pt
header-includes: 
    - \usepackage{amsmath}
    - \usepackage{ulem}    # text styles
    - \usepackage{tikz-cd} # graph
    - \usepackage{xeCJK}   # cjk
    # - \usepackage{fontspec}
    # - \newfontfamily\greekfont[Script=Greek]{NewComputerModern10}
    # - \usepackage{polyglossia}
    # - \setdefaultlanguage{english}
    - \usepackage{newcomputermodern}
    # line spacing
    - \usepackage{setspace}
    - \setstretch{1.15}
    # customized widgets
    # underline
    - \newcommand\highlight[1]{\raisebox{-2pt}{\uline{\raisebox{2pt}{#1}}}}
    # theorem 1
    - \usepackage{mdframed}
    - \newmdtheoremenv{thm-def}{Theorem}
    # theorem 2
    - \usepackage{tcolorbox}
    - \tcbuselibrary{theorems}
    - \newtcbtheorem[number within=section]{mydef}{Definition}{fonttitle=\bfseries}{th}
CJKmainfont: Source Han Serif SC
CJKoptions:
  - BoldFont=STKaiti
  - ItalicFont=STKaiti
---

# Aristotle 亚里士多德 (384 ~ 322 B.C.)

The rise of modern formal logic following the work of Frege and Russell brought with it a recognition of the many serious limitations of Aristotle’s logic.

However, Aristotle shares with modern logicians a fundamental interest in metatheory:

- His primary goal is not to offer a practical guide to argumentation but to study \highlight{the properties of inferential systems} themselves.

## The Organon

Aristotle's logical works, called the **Organon** are the earliest formal study of logic that have come down to modern times:

- **The Categories** ~ **范畴篇**, a study of the ten kinds of primitive terms.
- **On Interpretation** ~ **解释篇**, an analysis of simple **categorical propositions** into simple terms, negation, and signs of quantity.
- **The Prior Analytics** ~ **前分析篇**, a formal analysis of what makes a **syllogism**.
- **The Posterior Analytics** ~ **后分析篇**, a study of **scientific demonstration**, containing Aristotle's mature views on logic.
- **The Topics** ~ **论辩篇**, a discussion of **dialectics**.
- **On Sphistical Refutations** ~ **辩谬篇**

## Deduction

All Aristotle's logic revolves around **deduction** (συλλογισμός/sullogismos).

\begin{mydef*}{Deduction}
    A deduction is \textbf{speech} (λόγος/logos) in which, certain things having been supposed, something different from those supposed results of necessity because of their being so. (\textit{Prior Analytics} I.2, 24b19-20)
\end{mydef*}

Each of the "things supposed" is a **premise** (πρότασις/prótasis) of the argument, and what "result of necessity" is the **conclusion** (συμπέρασμα/sumperasma).


## The Syllogism

Syllogisms are structures of sentences each of which can meaningfully be called true or false: **assertions** (ἀποφανσεις/apophanseis), in Aristotle’s terminology. According to Aristotle, every such sentence must have the same structure: it must contain a **subject** (ὑποκειμενον/hupokeimenon) and a **predicate** and must either affirm or deny the predicate of the subject. Thus, every assertion is either the **affirmation** (καταφασις/kataphasis) or the **denial** (ἀποφασις/apophasis) of \highlight{a single predicate of a single subject}.

### The Square of Opposition

The square of opposition is a group of theses embodied in a diagram.
The theses concern logical relations among four logical forms:

|Name|Form|Title|
|:--:|:--:|:----|
|**A**|Every $S$ is $P$|Universal Affirmative|
|**E**|No $S$ is $P$|Universal Negative|
|**I**|Some $S$ is $P$|Particular Affirmative|
|**O**|Some $S$ is not $P$|Particular Negative|

\[\begin{tikzcd}
	{\text{Every S is P}} & {\textbf{A}} &&&& {\textbf{E}} & {\text{No S is P}} \\
	\\
	&&& {\text{contradictories}} \\
	\\
	{\text{Some S is P}} & {\textbf{I}} &&&& {\textbf{O}} & {\text{Some S is not P}}
	\arrow[no head, from=1-2, to=3-4]
	\arrow[no head, from=3-4, to=1-6]
	\arrow["{\text{subalterns}}"{description}, from=1-2, to=5-2]
	\arrow["{\text{subalterns}}"{description}, from=1-6, to=5-6]
	\arrow["{\text{subcontraries}}"{description}, no head, from=5-2, to=5-6]
	\arrow[no head, from=5-2, to=3-4]
	\arrow[no head, from=5-6, to=3-4]
	\arrow["{\text{contraries}}"{description}, no head, from=1-2, to=1-6]
\end{tikzcd}\]

---

# Chrysippus (279 ~ 206 B.C.)

Aristotelian logic was what was transmitted to the Arabic and the Latin medieval traditions, while the works of Chrysippus have not survived.

## Connective Logic

* $\cap, \quad \wedge, \quad \rightarrow$


